# Base Jekyll configuration

# Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Use _config.build.yml to override these settings on `grunt build`.

name: tonyrobbins
description: tonyrobbins.

author:
  name: Derek Blank
  email: dblank@centresource.com

# Exclude directories and/or files from the conversion.
# Grunt moves image files and the styles/scripts directories.
exclude: ['styles', 'scripts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: pretty

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: false

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']

# Use Pygments to highlight code blocks
pygments: true

styleguide_navigation:
- text: Typography
  url: /styleguide/typography/
- text: Color Palette
  url: /styleguide/palette/
- text: Media
  url: /styleguide/media/
- text: Form Elements
  url: /styleguide/form-elements/
- text: Layout
  url: /styleguide/layout/
- text: Tables
  url: /styleguide/tables/
- text: Carousels
  url: /styleguide/carousels/
- text: Member Portal
  url: /styleguide/member-portal/
- text: Shopping Cart
  url: /styleguide/shopping-cart/

